# Generated by Django 4.1.6 on 2023-02-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('blog', '0006_blogtagpageindex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogTagPageIndex',
            new_name='BlogTagIndexPage',
        ),
    ]
